"""Write heroes-js/js/original.js: the DATA statements of Heroes.exe and the shipped HEROES*.DAT presets."""
import json
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def parse_values(text):
    values = []
    for token in re.findall(r'"[^"]*"|[^,]+', text):
        token = token.strip()
        if not token:
            continue
        if token.startswith('"'):
            values.append(token[1:-1])
        else:
            number = float(token)
            values.append(int(number) if number.is_integer() and abs(number) < 1e9 else number)
    return values


def data_table():
    values, labels = [], {}
    for line in (ROOT / '.re' / 'heroes.bin.data').read_text().splitlines():
        label, text = line.split('  ', 1)
        labels[label] = len(values)
        values.extend(parse_values(text))
    return values, labels


def preset(path):
    raw = path.read_bytes()
    rec = lambda n: struct.unpack('<f', raw[(n - 1) * 4:n * 4])[0]
    num = lambda n: int(rec(n)) if float(rec(n)).is_integer() else rec(n)
    label = raw[140:148].decode('latin1').strip() if len(raw) >= 148 else path.stem
    return {
        'label': label or path.stem,
        'noLevelLimits': num(1) == 1,
        'classFocus': num(2),
        'breed': num(3),
        'rerollBelow': num(4),
        'method': num(5),
        'alignLimit': num(6),
        'names': num(7) == 1,
        'female': num(8),
        'breeds': num(9),
        'xpMin': num(10),
        'xpMax': num(13),
        # HEROES.CP edits the X.P. range as mantissa × 10^exponent and recomputes records 10 and 13 from these.
        'xpMinMant': num(11),
        'xpMinExp': num(12),
        'xpMaxMant': num(14),
        'xpMaxExp': num(15),
        'races': [num(n) for n in range(16, 25)],
        'social': [num(n) for n in range(26, 33)],
        'traits': num(34) != 0,
        'output': num(35),
    }


values, labels = data_table()
presets = [preset(ROOT / 'original' / f'HEROES{i}.DAT') for i in range(1, 13)]
default = preset(ROOT / 'original' / 'HEROES.DAT')

out = ROOT / 'heroes-js' / 'js' / 'original.js'
out.write_text(
    '// Generated by .re/export_js.py from the DATA statements of Heroes.exe and the shipped HEROES*.DAT files.\n'
    'window.Heroes = window.Heroes || {};\n'
    f'Heroes.DATA = {{ values: {json.dumps(values)}, labels: {json.dumps(labels)} }};\n'
    f'Heroes.DEFAULT_SETTINGS = {json.dumps(default)};\n'
    f'Heroes.PRESETS = {json.dumps(presets, indent=1)};\n'
)
print(len(values), 'values,', len(labels), 'labels,', len(presets), 'presets ->', out)
