// Decoded from HEROES.TRT (every byte of the original is shifted by +1).
// mods: ability magnitudes for [Str, Int, Wis, Dex, Con, Cha]; variants alternate +/-.
// Option prefixes: * limited trait, ^ humanoid-only trait, + "Great" may be prepended.
window.Heroes = window.Heroes || {};
Heroes.TRAITS = [
  {"mods": [0, 0, 0, 0, 0, 1], "options": ["Optimistic (Ch+1)", "Pessimistic (Ch-1)"]},
  {"mods": [2, 0, 0, 0, 2, 0], "options": ["Very healthy (C+2, S+2)", "Sickly (C-2, S-2)"]},
  {"mods": [0, 0, 0, 0, 0, 1], "options": ["Amiable (Ch+1)", "Rude (Ch-1)", "Agreeable (Ch+1)", "Argumentative (Ch-1)"]},
  {"mods": [0, 0, 0, 0, 0, 1], "options": ["Very persuasive (Ch+1)", "Undiplomatic (Ch-1)"]},
  {"mods": [0, 0, 0, 0, 0, 1], "options": ["Endearing habit (Ch+1) _____________", "Annoying habit (Ch-1) ______________"]},
  {"mods": [0, 0, 0, 0, 0, 2], "options": ["Aura of gentleness (Ch+2)", "Aura of meanness (Ch-2)", "Aura of benevolence (Ch+2)", "Aura of malevolence (Ch-2)"]},
  {"mods": [0, 0, 0, 0, 0, 1], "options": ["Very clean (Ch+1)", "Sloppy (Ch-1)", "Immaculate (Ch+1)", "Unkempt (Ch-1)", "Neat (Ch+1)", "Disheveled (Ch-1)"]},
  {"mods": [0, 0, 1, 0, 0, 0], "options": ["Level-headed (W+1)", "Quick to panic (W-1)"]},
  {"mods": [0, 0, 0, 0, 0, 1], "options": ["Brave (Ch+1)", "Cowardly (Ch-1)", "Courageous (Ch+1)", "Foolhardy (Ch-1)"]},
  {"mods": [0, 0, 0, 3, 0, 0], "options": ["Nimble (D+3)", "Clumsy (D-3)"]},
  {"mods": [0, 4, 0, 0, 0, 0], "options": ["Clever (I+4)", "Obtuse (I-4)", "Insightful (I+4)", "Dim-witted (I-4)"]},
  {"mods": [0, 0, 0, 0, 0, 3], "options": ["Beautiful (Ch+3)", "Ugly (Ch-3)"]},
  {"mods": [0, 0, 0, 0, 1, 0], "options": ["Resistant to drugs (C+1)", "Drug addict (C-1)", "Reformed drug addict (C+1)"]},
  {"mods": [0, 0, 0, 0, 2, 0], "options": ["Can sleep anywhere (C+2)", "Can't sleep (C-2)"]},
  {"mods": [0, 0, 0, 0, 3, 0], "options": ["Resistant to pain (C+3)", "Susceptible to pain (C-3)"]},
  {"mods": null, "options": ["Pipe smoker", "Hookah smoker", "Allergic to smoke", "Sensitive to smoke"]},
  {"mods": null, "options": ["Resistant to inebriation", "Alcoholic", "Reformed alcoholic", "Fond of wine", "Fond of drinking", "Fond of ale", "+Knowledge of wines & liquors"]},
  {"mods": null, "options": ["Albinic", "Unusually pigmented"]},
  {"mods": null, "options": ["^Long fingernails", "^Nail-biter"]},
  {"mods": null, "options": ["^Finger missing on right hand", "^3 fingers missing on right hand", "^Extra finger on right hand"]},
  {"mods": null, "options": ["^Finger missing on left hand", "^2 fingers missing on left hand", "^Extra finger on left hand"]},
  {"mods": null, "options": ["^Club-footed", "Limps", "Odd gait", "Bad knees"]},
  {"mods": null, "options": ["Youthful-appearing", "Mature-appearing"]},
  {"mods": null, "options": ["Severe allergy to ______________"]},
  {"mods": null, "options": ["Gluttonous", "Sparse eater"]},
  {"mods": null, "options": ["Chronic back pain"]},
  {"mods": null, "options": ["Chronic headaches", "Severe headaches"]},
  {"mods": null, "options": ["Allergic to furred animals"]},
  {"mods": null, "options": ["Skin affliction", "^Tattoo on face", "^Tattoo on arm", "^Tattoo on chest", "^Birthmark", "Hereditary mark"]},
  {"mods": null, "options": ["Allergic to dust & powder"]},
  {"mods": null, "options": ["Poor sense of smell", "Keen sense of smell"]},
  {"mods": null, "options": ["Small nose", "Sharp pointed nose", "Huge nose", "Big round nose", "Nose broken many times"]},
  {"mods": null, "options": ["^Small mouth", "^Huge mouth", "Thin lips", "Thick lips"]},
  {"mods": null, "options": ["^Striking smile", "^Bad teeth", "^Friendly smile", "^Jutting jaw", "^Buck-toothed", "^Overbite"]},
  {"mods": null, "options": ["Chronic cough"]},
  {"mods": null, "options": ["No sense of irony"]},
  {"mods": null, "options": ["Sweats excessively"]},
  {"mods": null, "options": ["Sunburns easily"]},
  {"mods": null, "options": ["Chronic sniffles"]},
  {"mods": null, "options": ["^Freckle-faced", "^Freckles on neck"]},
  {"mods": null, "options": ["^Moles on body", "^Mole on face"]},
  {"mods": null, "options": ["Blackouts: 3dC save once per day", "Severe blackouts: 5dC save thrice per day"]},
  {"mods": null, "options": ["Excellent vision", "Sees poorly", "*Blind", "Left eye gone", "Right eye gone", "Eyes different colors R___L___", "Susceptible to bright light", "Poor eyesight at dusk", "Wide-set eyes", "Close-set eyes", "Cataracts -- poor vision", "Penetrating gaze", "Impaired vision in full sunlight", "Pop-eyed", "Cross-eyed", "Cock-eyed"]},
  {"mods": null, "options": ["Hears poorly", "Hears keenly", "^Large ears", "^Left ear missing", "^Right ear missing"]},
  {"mods": null, "options": ["^Stained fingers (color _________ source _________)"]},
  {"mods": null, "options": ["Scar on face", "Scar on arm", "Terrible scar across face", "Several scars", "Burn scars across torso", "Burn scars on face"]},
  {"mods": null, "options": ["Losing hair", "Very hairy", "Odd hairstyle", "Bald", "Shaved head"]},
  {"mods": null, "options": ["Underweight", "Overweight"]},
  {"mods": null, "options": ["Tall", "Short"]},
  {"mods": null, "options": ["Susceptible to cold (double damage)", "Susceptible to heat (double damage)"]},
  {"mods": null, "options": ["Intricate personality -- varying beliefs", "Shallow personality", "Complex personal contradictions"]},
  {"mods": null, "options": ["Lack of motivation", "Strongly motivated", "Broken-spirited", "Quick-tempered", "Hopeful", "Fatalistic"]},
  {"mods": null, "options": ["Thoughtful", "Thoughtless", "Highly empathic", "Uncaring towards others"]},
  {"mods": null, "options": ["Strong personal aura of ________________"]},
  {"mods": null, "options": ["Alert -- always noticing things", "Inattentive -- easily confused", "Poor memory", "Forgetful", "Short attention span"]},
  {"mods": null, "options": ["Greedy", "Generous", "Wasteful", "Frugal", "Thrifty", "Miserly", "Selfish"]},
  {"mods": null, "options": ["Stubborn", "Obstinate", "Petulant", "Arrogant", "Cooperative", "Condescending"]},
  {"mods": null, "options": ["Conservative", "Liberal", "Old-fashioned", "Progressive"]},
  {"mods": null, "options": ["Curious", "Apathetic"]},
  {"mods": null, "options": ["Solemn", "Hyperactive", "Lazy"]},
  {"mods": null, "options": ["Cautious", "Impulsive"]},
  {"mods": null, "options": ["Accident-prone"]},
  {"mods": null, "options": ["Idealist"]},
  {"mods": null, "options": ["Honest", "Dishonest", "Scrupulous", "Devious", "Straight-forward"]},
  {"mods": null, "options": ["Perfectionist"]},
  {"mods": null, "options": ["Introverted", "Extroverted"]},
  {"mods": null, "options": ["Trusting", "Paranoid"]},
  {"mods": null, "options": ["Manic-depressive"]},
  {"mods": null, "options": ["Devil's advocate"]},
  {"mods": null, "options": ["Logical", "Illogical"]},
  {"mods": null, "options": ["Mild hallucinations", "*Severe hallucinations"]},
  {"mods": null, "options": ["Independent -- will not take orders"]},
  {"mods": null, "options": ["Favorite saying under stress: `___________________________'"]},
  {"mods": null, "options": ["Favorite saying upon failure: `___________________________'"]},
  {"mods": null, "options": ["Favorite taunt in combat: `_______________________________'"]},
  {"mods": null, "options": ["Favorite saying upon success: `___________________________'"]},
  {"mods": null, "options": ["Favorite sarcastic witticism: `___________________________'"]},
  {"mods": null, "options": ["Obsession _________________________________"]},
  {"mods": null, "options": ["Compulsion ________________________________"]},
  {"mods": null, "options": ["+Hatred of ________________________________"]},
  {"mods": null, "options": ["Deathly fear of ______________________ (extreme panic)"]},
  {"mods": null, "options": ["+Devotion to ______________________________"]},
  {"mods": null, "options": ["+Suspicion of _____________________________", "+Trust in _____________________"]},
  {"mods": null, "options": ["Sexual fetish ________________________", "Nymphomaniac", "Sexual preference for ___________", "Impotent", "Sexually charming"]},
  {"mods": null, "options": ["Prophetic dreams"]},
  {"mods": null, "options": ["Recurrent nightmares"]},
  {"mods": null, "options": ["Gullible"]},
  {"mods": null, "options": ["Humble", "Huge ego", "Inferiority complex", "Conceited", "Simple-mannered"]},
  {"mods": null, "options": ["Determined (two attempts when usually allowed one)", "Easily frustrated"]},
  {"mods": null, "options": ["Uneasy around other races"]},
  {"mods": null, "options": ["Talkative", "Taciturn", "Speaks in an unusual pattern", "Mute", "Rough-voiced", "Smooth-voiced", "Tongue cut out", "Stutters", "Vocal cords damaged -- can only whisper", "Speaks in tongues", "Uses vulgar language"]},
  {"mods": null, "options": ["Kleptomaniac", "Respect for other's property"]},
  {"mods": null, "options": ["+Fear of spiders"]},
  {"mods": null, "options": ["+Fear of children"]},
  {"mods": null, "options": ["+Fear of elders"]},
  {"mods": null, "options": ["+Fear of corpses", "+Fear of dead bodies", "+Fear of dead things"]},
  {"mods": null, "options": ["+Fear of water"]},
  {"mods": null, "options": ["+Fear of heights", "Terrified of falling"]},
  {"mods": null, "options": ["+Fear of insects"]},
  {"mods": null, "options": ["+Fear of the opposite sex"]},
  {"mods": null, "options": ["+Fear of ghosts & spirits"]},
  {"mods": null, "options": ["+Fear of being wounded"]},
  {"mods": null, "options": ["+Fear of the dark"]},
  {"mods": null, "options": ["+Fear of dragons"]},
  {"mods": null, "options": ["+Fear of damnation"]},
  {"mods": null, "options": ["Confrontational", "+Fear of personal confrontation"]},
  {"mods": null, "options": ["+Fear of being captured/restrained"]},
  {"mods": null, "options": ["+Fear of embarrasment", "Fear of humiliation"]},
  {"mods": null, "options": ["+Fear of rodents"]},
  {"mods": null, "options": ["+Fear of demons & underworld creatures"]},
  {"mods": null, "options": ["+Fear of personal failure"]},
  {"mods": null, "options": ["+Fear of reptiles", "+Fear of lizards"]},
  {"mods": null, "options": ["+Fear of fire", "Terrified of open flames", "+Fear of being burned"]},
  {"mods": null, "options": ["Claustrophobic"]},
  {"mods": null, "options": ["Intrigued by shiny objects", "Befuddled by objects of stone"]},
  {"mods": null, "options": ["+Appreciation of tapestries & murals"]},
  {"mods": null, "options": ["+Appreciation of paintings", "*+Painter"]},
  {"mods": null, "options": ["+Appreciation of poetry", "*+Poet"]},
  {"mods": null, "options": ["Good luck (+2 on all saving throws)", "Bad luck (-2 on all saving throws)"]},
  {"mods": null, "options": ["Preparedness"]},
  {"mods": null, "options": ["Plays the lute", "^Plays the flute", "^Plays the brass horn", "^Plays the pan pipes", "Plays musical instrument ____________", "Good singing voice", "^Likes to hum tunelessly", "Poor but loud singer", "Good whistler", "^Does bird-calls", "No sense of music", "No sense of rhythm", "Hates music", "Hypnotized by music"]},
  {"mods": null, "options": ["+Mechanical aptitude"]},
  {"mods": null, "options": ["Collector of ___________________"]},
  {"mods": null, "options": ["Good with animals, good horseman"]},
  {"mods": null, "options": ["Clairvoyant"]},
  {"mods": null, "options": ["Clairaudient"]},
  {"mods": null, "options": ["Clairsentient"]},
  {"mods": null, "options": ["Photographic memory", "Audiographic memory"]},
  {"mods": null, "options": ["Thinks conceptually -- has intuitive flashes"]},
  {"mods": null, "options": ["Born cultivator -- good with plants"]},
  {"mods": null, "options": ["Born swimmer", "Can't swim", "*Gills -- can breathe underwater"]},
  {"mods": null, "options": ["Born climber", "Can't climb"]},
  {"mods": null, "options": ["Healing hands (d6 points once/day)"]},
  {"mods": null, "options": ["+Haggler", "+Skills in negotiation"]},
  {"mods": null, "options": ["+Weaver"]},
  {"mods": null, "options": ["+Carpenter"]},
  {"mods": null, "options": ["+Whittler", "+Wood carver", "+Stone carver", "+Marble sculptor", "+Appreciation of sculpture"]},
  {"mods": null, "options": ["Trance ability (once/wk for d12 hrs, heal all damage)"]},
  {"mods": null, "options": ["+Knowledge of gems"]},
  {"mods": null, "options": ["+Knowledge of herbology"]},
  {"mods": null, "options": ["+Knowledge of cheeses", "Allergic to dairy products"]},
  {"mods": null, "options": ["+Knowledge of fibers & fabric"]},
  {"mods": null, "options": ["+Knowledge of cultures"]},
  {"mods": null, "options": ["+Knowledge of races & breeds"]},
  {"mods": null, "options": ["+Knowledge of geography"]},
  {"mods": null, "options": ["+Skills in first aid"]},
  {"mods": null, "options": ["+Knowledge of weapons"]},
  {"mods": null, "options": ["+Knowledge of history"]},
  {"mods": null, "options": ["+Military strategist", "Caught up in details", "Large-scale thinking", "Wide scope of vision & understanding"]},
  {"mods": null, "options": ["+Knowledge of theology"]},
  {"mods": null, "options": ["+Knowledge of animals"]},
  {"mods": null, "options": ["+Knowledge of plants"]},
  {"mods": null, "options": ["+Knowledge of monsters"]},
  {"mods": null, "options": ["+Knowledge of farming"]},
  {"mods": null, "options": ["+Knowledge of humanoid psychology"]},
  {"mods": null, "options": ["+Knowledge of nature"]},
  {"mods": null, "options": ["+Knowledge of liquids"]},
  {"mods": null, "options": ["+Knowledge of soils"]},
  {"mods": null, "options": ["+Knowledge of crystals"]},
  {"mods": null, "options": ["+Knowledge of weather"]},
  {"mods": null, "options": ["+Knowledge of alchemy"]},
  {"mods": null, "options": ["+Knowledge of legends"]},
  {"mods": null, "options": ["+Knowledge of hunting"]},
  {"mods": null, "options": ["+Knowledge of writing forms"]},
  {"mods": null, "options": ["+Knowledge of food"]},
  {"mods": null, "options": ["+Knowledge of jewelry"]},
  {"mods": null, "options": ["+Knowledge of coins & money"]},
  {"mods": null, "options": ["+Knowledge of metals & ores"]},
  {"mods": null, "options": ["+Knowledge of modern languages"]},
  {"mods": null, "options": ["+Knowledge of ancient languages"]},
  {"mods": null, "options": ["Keeps a journal"]},
  {"mods": null, "options": ["Parents killed by goblins", "Family outcast from homeland", "Parents unknown", "Parents enslaved by evil mage", "Orphan", "Parents eaten by dragon", "Raised by unicorns", "Raised by griffons", "Royal family -- grandchild of true king", "Royal family -- distant cousin of true king"]},
  {"mods": null, "options": ["Sister sacrificed by evil priest", "Brother killed in combat"]},
  {"mods": null, "options": ["Favorite item ____________________________________ (depression if lost)"]},
  {"mods": null, "options": ["Member of secret group ________________________________"]},
  {"mods": null, "options": ["Nickname/alias ________________________________________"]},
  {"mods": null, "options": ["Dependent NPC ____________rc___hp(__) cl__lv__*_________"]},
  {"mods": null, "options": ["Animal companion __________hd__hp(__) ac__dm__*_________", "*Monster companion _________hd__hp(__) ac__dm__*_________"]},
  {"mods": null, "options": ["Minor mutation __________", "*Major mutation __________"]},
  {"mods": null, "options": ["*Amnesiac -- recently lost all memory", "*Amnesiac -- lost all memory several years ago"]},
  {"mods": null, "options": ["*Wings -- class A, 30''", "*Wings -- class B, 24''", "*Wings -- class C, 18''"]},
  {"mods": null, "options": ["*Polymorphed into orc-form", "*Polymorphed into goblin-form", "*Polymorphed into ape-form", "*Polymorphed into kobold-form"]},
  {"mods": null, "options": ["*Vampiric"]},
  {"mods": null, "options": ["*Suicidal"]},
  {"mods": null, "options": ["*Immortal (immune to death by old age)"]},
  {"mods": null, "options": ["*Lycanthropic (werewolf)", "*Lycanthropic (werebird)", "*Lycanthropic (wereboar)", "*Lycanthropic (special wereform ___________)"]},
  {"mods": null, "options": ["*Lack of astral integrity"]},
  {"mods": null, "options": ["*Permanently invisible"]},
  {"mods": null, "options": ["*Multiple secondary personalities (varying alignments)"]},
  {"mods": null, "options": ["*Hypnotic pyromaniac", "*Frenzied pyromaniac"]},
  {"mods": null, "options": ["*Detachable body part _____________"]},
  {"mods": null, "options": ["*Liar", "Always tries to keep promises", "Rarely tries to keep promises", "Never tries to keep promises"]},
  {"mods": null, "options": ["*Regenerates 1-2hp/round", "*Regenerates d4hp/round", "*Hemophiliac -- loses d4hp/round if cut"]},
  {"mods": null, "options": ["*Hunchback"]},
  {"mods": null, "options": ["Minor delusion _____________________", "*Severe delusion ___________________", "*Schizophrenic", "*Lunatic"]},
  {"mods": [4, 4, 4, 4, 4, 4], "options": ["*True Hero (SIWDCCh+4) -- Beloved by everyone! All faults overlooked!"]}
];
